# Generated by Django 5.0.7 on 2024-07-22 00:58

import booking.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateTimeField(default=booking.models.default_travel_date),
        ),
        migrations.AddField(
            model_name='vehicleroute',
            name='price',
            field=models.DecimalField(decimal_places=3, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transportationcompany',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='transportationcompany',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain only digits', regex='^\\d+$')]),
        ),
    ]
