# Generated by Django 5.0.7 on 2024-08-03 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_children_above_10',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('ONE WAY', 'one way ticket'), ('TWO WAY', 'two way ticket')], default='ONE WAY', max_length=25),
        ),
        migrations.CreateModel(
            name='VehicleSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_datetime', models.DateTimeField()),
                ('number_of_bookings', models.PositiveIntegerField(default=0)),
                ('destination_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_destination_state', to='booking.state')),
                ('pickup_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_pickup_state', to='booking.state')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.vehicle')),
            ],
        ),
    ]
