# Generated by Django 5.0.7 on 2024-08-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminals',
            name='area',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
