# Generated by Django 5.0.7 on 2024-08-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_terminals_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminals',
            name='area',
            field=models.CharField(max_length=50),
        ),
    ]
