# Generated by Django 5.0.7 on 2024-07-28 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_vehicle_price_booking_travel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicleroute',
            name='state',
        ),
        migrations.AddField(
            model_name='vehicleroute',
            name='state1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='state1_travelled_to', to='booking.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleroute',
            name='state2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='state2_travelled_to', to='booking.state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='phone',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='state',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='terminal1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='terminal2',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
