# Generated by Django 5.0.7 on 2024-08-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_terminals_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleschedule',
            name='travel_datetime',
            field=models.DateField(),
        ),
    ]
