# Generated by Django 5.0.7 on 2024-07-29 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_user_remove_vehicleroute_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destination_state',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_state',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='terminal1',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='terminal2',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicleroute',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.vehicle'),
        ),
    ]
