# Generated by Django 5.0.7 on 2024-08-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_vehicleschedule_travel_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleschedule',
            name='travel_datetime',
            field=models.DateTimeField(),
        ),
    ]
