# Generated by Django 5.0.7 on 2024-08-20 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_vehicleschedule_travel_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationcompany',
            name='slug',
        ),
    ]
